@ECHO OFF
SET APPPATH=%CD%
SET APPLOG=%APPPATH%\logs
SET SCRIPTAPP=c:\windows\SysWOW64\cscript.exe
SET VBSCRIPT=%1
SET LOGFILE=%APPLOG%\%VBSCRIPT%

%SCRIPTAPP% /nologo %APPPATH%\%VBSCRIPT%.vbs >> %LOGFILE%
